# Generated by Django 5.0.3 on 2024-04-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='utilisateures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(default='kfb@gmail.com', max_length=254)),
                ('message', models.TextField(default='message')),
            ],
        ),
    ]
