# Generated by Django 5.0.3 on 2024-04-05 23:49

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="Date d'ajout")),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='titre')),
                ('subtitle', models.CharField(default='', max_length=255, verbose_name='texte présentatif')),
                ('description', tinymce.models.HTMLField(max_length=50000, verbose_name="description de l'évènement")),
                ('start_at', models.DateTimeField(null=True, verbose_name='date de début')),
                ('end_at', models.DateTimeField(null=True, verbose_name='date de fin')),
                ('published', models.BooleanField(default=True, verbose_name='publié')),
                ('illustration_image', models.ImageField(upload_to='images/events/%Y/%m/%d', verbose_name="image d'illustration")),
                ('illustration_video', models.CharField(blank=True, max_length=1000, null=True, verbose_name="lien de la vidéo d'illustration")),
            ],
            options={
                'verbose_name': 'évènement',
                'verbose_name_plural': 'évènements',
            },
        ),
    ]
